"""Add filesize field to Document

Revision ID: 1f59bc738dfc
Revises: 
Create Date: 2025-07-29 15:04:10.607666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f59bc738dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))
        batch_op.alter_column('uploader_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('download_log', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('download_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('uploader_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('filesize')

    # ### end Alembic commands ###
