"""Add phone_number, default role Pending, nullable unit_number

Revision ID: b7c217ebb0cb
Revises: f20399b84b1e
Create Date: 2025-07-29 19:51:02.972937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c217ebb0cb'
down_revision = 'f20399b84b1e'
branch_labels = None
depends_on = None


def upgrade():
    # Set default for existing users BEFORE altering table
    op.execute("UPDATE user SET role = 'Pending' WHERE role IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
            existing_type=sa.String(length=50),
            nullable=False,
            server_default='Pending'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
