"""Add archived and mimetype to Document

Revision ID: c8e665e5a12f
Revises: 1f59bc738dfc
Create Date: 2025-07-29 16:07:15.599699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e665e5a12f'
down_revision = '1f59bc738dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('archived')
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###
